# Generated by Django 5.0.6 on 2024-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('health_beauty', 'Health & Beauty'), ('home_garden', 'Home & Garden'), ('sports_outdoors', 'Sports & Outdoors'), ('toys_hobbies', 'Toys & Hobbies'), ('books_media', 'Books & Media'), ('food_beverages', 'Food & Beverages'), ('automotive', 'Automotive'), ('pet_supplies', 'Pet Supplies')], max_length=50),
        ),
    ]
